# Generated by Django 5.1.1 on 2024-09-04 14:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcar',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Not in country', 'Not in country')], default='Sofia', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evcar',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatch', 'Hatchback'), ('Station wagon', 'Station wagon'), ('Coupe', 'Coupe'), ('SUV', 'SUV')], default='unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='range',
            field=models.IntegerField(default=None, help_text='WLTP rating', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
