# Generated by Django 5.1.1 on 2024-09-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_evcar_location_alter_evcar_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='cars.carbrand'),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='cars.carmodel'),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.user'),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='vin',
            field=models.CharField(default='unknown', help_text='Vehicle Identification Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, default='staticfiles/images/icon_image.png', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name')},
        ),
    ]
