# Generated by Django 5.1.1 on 2024-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carbrand_name_alter_carmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcar',
            name='trim_level',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
