# Generated by Django 5.1.1 on 2024-09-10 14:18

import EvTools2.cars.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_evcar_trim_level_alter_evcar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evcar',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the EV', upload_to='ev_photos/'),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Varna', 'Varna'), ('Burgas', 'Burgas'), ('Not in country', 'Not in country')], max_length=30),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='vin',
            field=models.CharField(default='unknown', help_text='Vehicle Identification Number', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(EvTools2.cars.models.current_year)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address. Your email will be displayed only if you decide', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter a phone number. No dashes, slashes or spaces are allowed. Your number will be displayed only if you decide', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 12 digits long, can start with +, no spaces, slashes and dashes.', regex='^\\+?(\\d+){9,}$')]),
        ),
        migrations.CreateModel(
            name='EVPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a photo of the EV', upload_to='ev_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ev_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.evcar')),
            ],
        ),
    ]
