# Generated by Django 5.1.1 on 2024-09-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_evcar_photo_alter_evcar_location_alter_evcar_vin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcar',
            name='photo',
        ),
    ]
