# Generated by Django 5.1.1 on 2024-09-10 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_evcar_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EVPhoto',
            new_name='EVCarPhoto',
        ),
        migrations.RenameField(
            model_name='evcarphoto',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='Enter a nickname between 3 and 30 characters. Only letters, numbers, underscores, and hyphens are allowed.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Nickname must be between 3 and 30 characters long and can include letters, numbers, underscores, and hyphens.', regex='^[A-Za-z0-9_-]{3,30}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Enter a phone number. No dashes, slashes, or spaces are allowed. Your number will be displayed only if you decide', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 12 digits long, can start with +, no spaces, slashes and dashes.', regex='^\\+?(\\d+){9,}$')]),
        ),
    ]
