# Generated by Django 5.1.1 on 2024-09-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_evphoto_evcarphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcar',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True),
        ),
    ]
